title: Programming Notes
author: Jeong Deokin
email: jjwdi0@snu.ac.kr
description: > # this means to ignore newlines until "show_exerpts:"
  No description yet
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: 
url: https://jjwdi0.github.io/

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

timezone: Asia/Seoul

permalink: /posts/:title/
texture:
  title: Programming Notes
  tagline: 
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  showPicker: false

  # generate social links in footer
  social_links:
    github:  jjwdi0

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed